[workspace]
members = [
    "auth-api",
    "auth-service",
    "bot-service",
    "chat-service",
    "gateway-service",
    "history-service",
    "presence-service",
    "proto",
    "net",
    "unhidra-snapshots"
, "unhidra-snapshot-gui"]

resolver = "2"
