[package]
name = "bot-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48", features = ["full"] }
proto = { path = "../proto" }
serde_json = "1.0"
tokio-tungstenite = "0.28.0"
